### ISSUE TITLE
No info about travis addon

### ISSUE THREAD

**Issue by antonmarin** [codeclimate/php-test-reporter#53] opened 2016-06-05 09:03 UTC
No info about how to configure travis addon to use custom coverage-report file 
(test-reporter [--coverage-report COVERAGE-REPORT])

For example:

```
addons:
    code_climate:
        repo_token: ****
        coverage_report: tests/logs/clover.xml
```

**Comment by dblandin** [comment] 2016-06-07 18:52
@antonmarin Agreed that this repo should at least link to TravisCI's [documentation][addon] for the Code Climate addon.

@1ma As far as I know, you shouldn't have to configure Code Climate as an addon _and_ add the environment variable separately within your TravisCI repo config.

[addon]: https://docs.travis-ci.com/user/code-climate

From what I've gathered, the intended behavior of the addon should be to install the correct test reporter automatically given your repo language and set the right env variable from the `repo_token` config.

Hopefully that's the case using the addon with a php repo, although I did run into an issue recently configuring the addon for a javascript project: https://github.com/codeclimate/javascript-test-reporter/pull/37. I ended up installing the test reporter manually just before sending the report as a workaround.

**Comment by pbrisbin** [comment] 2017-01-11 15:49
It looks like we have some Travis-specific docs available [here](https://docs.codeclimate.com/docs/travis-ci-php-test-coverage).

In general, our aim is to centralize documentation on docs.codeclimate.com and link to those from succinct project README's -- to avoid duplication and confusion. This project's README hasn't been rewritten in that style yet, but when it is we should include a link to these docs, and that should close this Issue IMO.

**Comment by carbontwelve** [comment] 2017-01-11 16:17
The documentation on the codeclimate is awful with respect to travis-ci usage. I have had a few builds complete after simply adding the following:

```
addons:
    code_climate:
        repo_token: ***
```

and I still get an unknown code coverage, with travis-ci logs showing nothing done with regards to codeclimate.

The available documentation doesn't even mention the need to use travis-ci environment variables to keep the key hidden.

**Comment by RobertShippey** [comment] 2017-03-04 00:36
I agree with @carbontwelve - the documentation on setting this up is mystifying. The doc pages seem to circularly link to each other with none of them adding helpful info 😢

**Comment by antonmarin** [comment] 2017-03-04 10:06
I think that covering usage of travis environments on the [page](https://docs.codeclimate.com/docs/travis-ci-php-test-coverage) is enough to successfully setup

**Comment by carbontwelve** [comment] 2017-03-08 11:41
I couldn't get the code coverage to work with the travis integration, which is likely because some of my tests change the current working directory and therefore phpunit doesn't save the clover xml file where the test-reporter is expecting it (I am still not sure where on my machine it saved the file to, because I can't find it unless I provide an absolute output path.)

I ended up fixing this with the following (which are now only executed once for one version of PHP):

```
vendor/bin/phpunit --coverage-clover=$TRAVIS_BUILD_DIR/build/logs/clover.xml
vendor/bin/test-reporter
```

Does the travis-ci integration set an absolute path for `--coverage-clover` as per my example above? Because sometimes phpunit will not save the output where you expect it to be if you only provide a relative path.

**Comment by jhabdas** [comment] 2017-05-15 11:01
Given I've had some experience and worked my way through a few different docs to set-up coverage reporting using the addon I agree it should be more clearly documented in the README or the README updated to point specifically (and only) to the CodeClimate docs site so the info doesn't go stale. That said, I followed all the docs and flubbed on the following:

- Forgot to prefix my CI env var with `$`, so instead of `$CODECLIMATE_REPO_TOKEN` I had `CODECLIMATE_REPO_TOKEN`. Kind of a dumb move on my part, but worth noting in the docs by way of example as shown by @1ma above.
- Keep getting the following issue (which could be hard to miss as you may have to dig through CI logs to find it: `vendor/bin/test-reporter: No such file or director`. I have the `php-test-reporter` being installed via composer and I've tried it using both of the `--dev` installation settings (the ones shown in the README of this repo and those found in the CodeClimate docs site) and neither of them worked. So I assume I need to install the reporter as a dependency and not a dev dependency as I imagine Travis isn't installing the dev deps. Anyway. That was my FUX.

**Comment by jhabdas** [comment] 2017-05-15 11:08
@pbrisbin when updating the docs site to close this issue please consider also adding a note regarding the use of the `phpunit.xml.dist` file as opposed to the CLI flag as it's not currently part of the documentation and something users of things like the [`wp-cli`](https://github.com/wp-cli/wp-cli) will find useful after creating their [conventional test scaffolds](https://github.com/wp-cli/sample-plugin).

**Comment by jhabdas** [comment] 2017-05-15 13:03
Another issue here in the docs: https://docs.codeclimate.com/docs/travis-ci-php-test-coverage#section--troubleshooting-

Travis no longer uses the phrase `Build pushes` they use `Build branch updates`.

**Comment by jhabdas** [comment] 2017-05-16 04:59
Potential root cause: https://github.com/codeclimate/codeclimate/issues/660

**Comment by dblandin** [comment] 2017-09-19 22:00
Hey @antonmarin,

Thank for the issue. We're winding down development on this PHP-specific reporter.

I'd recommend checking out our new test reporter and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉 

We've also worked with Travis CI on an update to their Code Climate documentation which you can find here: https://docs.travis-ci.com/user/code-climate/

**Closed by dblandin** 2017-09-19 22:00 UTC
